githubSecret: ""
alert:
  enabled: false
schedule: "*/2 * * * *"
image:
  repository: "europe-north1-docker.pkg.dev/nais-io/nais/images/ingress-to-terraform-dns"
  tag: "master"
  pullPolicy: IfNotPresent

dnsZone: "dnszone"
recordIP: "recordip"
ingressSuffix: "ingresssuffix"
ignoreIngressSuffix: "ignoreingressuffix"
ignoreIngresses: "ignoreingresses"
recordsFilePath: "recordsfilepath"
httpProxy: "http://webproxy-nais.nav.no:8088"
noProxy: "10.254.0.1"

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532
