name: ingress-to-terraform-dns release pipeline

on: [push]

env:
  image: docker.pkg.github.com/${{ github.repository }}/ingress-to-terraform-dns

jobs:
  build:
    name: Release to GHPR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate image environment variable
        run: |
          version=$(./version.sh)
          echo "version=${version}" >> $GITHUB_ENV
          echo "IMAGE=${image}:${version}" >> $GITHUB_ENV
      - name: Build Docker image
        run: docker build . --tag $IMAGE
      - name: Login to Github package registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "$GITHUB_TOKEN" | docker login docker.pkg.github.com -u "$GITHUB_REPOSITORY" --password-stdin
      - name: Push docker image
        run: docker push $IMAGE
  deploy:
    name: Deploy to Kubernetes
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Generate image environment variable
      run: |
        version=$(./version.sh)
        echo "version=${version}" >> $GITHUB_ENV
        echo "IMAGE=${image}:${version}" >> $GITHUB_ENV
        echo "NAIS_YAML=${GITHUB_WORKSPACE}/nais-yaml" >> $GITHUB_ENV
        pwd
    - name: Bump version in nais-yaml
      env:
        DEPLOY_KEY: ${{ secrets.NAIS_YAML_DEPLOY_KEY }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${DEPLOY_KEY}"
        mkdir -p $NAIS_YAML
        git clone git@github.com:navikt/nais-yaml.git $NAIS_YAML
        cd $NAIS_YAML
        git config user.email "aura@nav.no"
        git config user.name "NAIS deploy pipeline"
        sed -E -i "s#image: docker.pkg.github.com/nais/ingress-to-terraform-dns/ingress-to-terraform-dns:.+#image: ${IMAGE}#" vars/global.yaml
        git add .
        git --no-pager diff --cached
        git commit --no-verify -a -m "Bump ingress-to-terraform-dns to version ${version}"
        git push
