name: ingress-to-terraform-dns release pipeline

on: [push]

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  build:
    name: Release to GHPR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run npm tests
        run: docker build --target test .
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}

  deploy:
    name: Deploy to Kubernetes
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: navikt/github-app-token-generator@v1
      id: get-token
      with:
        private-key: ${{ secrets.NAIS_APP_PRIVATE_KEY }}
        app-id: ${{ secrets.NAIS_APP_ID }}
        repo: navikt/nais-yaml
    - uses: actions/checkout@v2
      with:
        repository: navikt/nais-yaml
        token: ${{ steps.get-token.outputs.token }}
        path: nais-yaml
    - name: Bump version in nais-yaml
      run: |
        cd nais-yaml
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        sed -E -i "s#image: ghcr.io/${GITHUB_REPOSITORY}:.+#image: ${IMAGE}#" vars/global.yaml
        git add .
        git --no-pager diff --cached
        git commit --no-verify -a -m "Bump ingress-to-terraform-dns to version ${version}"
        git push
